enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = true
wood_you_dye = true
bountiful = true
farmersdelight = true
spelunkery = true
mutantmonsters = true
mythicmobs = true
alloy_forgery = true
croptopia = true
betternether = true
brewery = true
festive_delight = true
immersive_portals = true
runes = true
friendsandfoes = true
mini_scaled = true
twigs = true
bitsandchisels = true
powah = true
entangled = true
mcwbridges = true
railways = true
additionaladditions = true
the_bumblezone = true
handcrafted = true
power_networks = true
modern_industrialization = true
spell_engine = true
casualness_delight = true
nightlights = true
techreborn = true
cccbridge = true
advanced_networking = true
paladins = true
beachparty = true
endrem = true
create = true
windchimes = true
extended_drawers = true
wormhole = true
additionallanterns = true
createoreexcavation = true
minecraft = true
animal_feeding_trough = true
travelersbackpack = true
createaddition = true
display_case = true
adventurez = true
sliceanddice = true
waystones = true
dragonloot = true
carpeted = true
expandeddelight = true
bushierflowers = true
cinderscapes = true
seasonsextras = true
betterfurnacesreforged = true
connectedglass = true
betterend = true
mythicupgrades = true
createutilities = true
ends_delight = true
milk = true
chunkloaders = true
extendedgears = true
advancednetherite = true
amethyst_imbuement = true
graveyard = true
indrev = true
ubesdelight = true
garnished = true
chipped = true
clutter = true
terrestria = true
soulsweapons = true
trashcans = true
lootr = true
expandedstorage = true
merequester = true
regions_unexplored = true
wardentools = true
betterarcheology = true
chococraft = true
ae2 = true
jewelry = true
beautify = true
voidz = true
traverse = true
computercraft = true
universal_graves = true
villagersplus = true
vinery = true
grapplemod = true
meadow = true
ad_astra = true
ad_astra_giselle_addon = true
mythicmetals = true
