# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				axolotl = true
				donkey = true
				cow = true
				fox = true
				tropical_fish = true
				slime = true
				pig = true
				pillager = true
				skeleton = true
				area_effect_cloud = true
				bat = true
				rabbit = true
				cat = true
				zombie = true
				armor_stand = true
				drowned = true
				sheep = true
				player = true
				illusioner = true
				dolphin = true
				item = true
				potion = true
				villager = true
				wolf = true
				skeleton_horse = true
				salmon = true
				zombie_villager = true
				tnt_minecart = true
				ocelot = true
				item_frame = true
				polar_bear = true
				horse = true
				vindicator = true
				minecart = true
				painting = true
				evoker = true
				cave_spider = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true
				stray = true
				cod = true
				turtle = true
				frog = true
				ravager = true
				panda = true
				pufferfish = true
				husk = true
				arrow = true
				goat = true
				wither_skeleton = true
				blaze = true
				zombified_piglin = true
				magma_cube = true
				piglin = true
				strider = true
				small_fireball = true
				ender_dragon = true
				experience_orb = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				nameless_hanged = true
				revenant = true
				corrupted_vindicator = true
				skeleton_creeper = true
				corrupted_pillager = true
				ghoul = true
				nightmare = true

			[light_sources.settings.entities.bewitchment]
				ghost = true
				raven = true
				owl = true
				snake = true
				toad = true
				werewolf = true

			[light_sources.settings.entities.clutter]
				mossbloom = true
				kiwi_bird = true
				chameleon = true
				echofin = true

			[light_sources.settings.entities.adventurez]
				deer = true
				amethyst_golem = true
				mammoth = true
				ender_whale = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_zombie = true
				mutant_skeleton = true
				mutant_creeper = true

			[light_sources.settings.entities.chococraft]
				chocobo = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				iceologer = true
				mauler = true

			[light_sources.settings.entities.mythicmobs]
				kobold_warrior = true
				automaton = true
				mushroom_thing = true
				kobold = true
				drake = true
				chupacabra = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.meadow]
				brown_bear = true
				wooly_cow = true

			[light_sources.settings.entities.wildlife]
				snail = true
				rhino_beetle = true
				spicebush_butterfly = true
				bettafish = true
				koi = true
				bluegill = true
				possum = true
				hammerhead_shark = true
				ladybug = true
				stingray = true
				catfish = true
				sanddollar = true
				dragonfly = true
				robin = true
				goldfish = true
				king_snake = true
				staghorn_beetle = true
				rainbow_trout = true
				glasswing_butterfly = true
				sparrow = true
				porcupine = true
				lark = true
				tiger_butterfly = true
				starfish = true
				phoebe = true
				mantaray = true
				june_beetle = true
				flycatcher = true
				ant = true
				stickbug = true
				monarch_butterfly = true
				prawn = true
				grass_snake = true
				bluebird = true
				sunflowerbeetle = true
				goldfinch = true
				badger = true
				wren = true
				gecko = true
				hedgehog = true
				horseshoecrab = true
				cricket = true
				ferret = true
				spider = true
				white_eye = true
				clam = true
				seaurchin = true
				seahorse = true
				morpho_butterfly = true
				beaver = true
				deer = true
				boar = true
				crab = true
				hamster = true
				armadillo = true
				python = true

			[light_sources.settings.entities.wilderwild]
				tumbleweed = true
				firefly = true
				jellyfish = true

			[light_sources.settings.entities.soulsweapons]
				big_chungus = true

			[light_sources.settings.entities.immersive_portals]
				loading_indicator = true
				nether_portal_new = true
				end_portal = true

			[light_sources.settings.entities.betternether]
				hydrogen_jellyfish = true
				firefly = true

